USE AdventureWorks2019;

--  Find Foreign Key in a Table
	-- Way 1: Directly in Object Explorer : Tables -> HumanResources.EmployeePayHistory -> Keys
	-- Way 2: From INFORMATION_SCHEMA
SELECT 
TC.CONSTRAINT_SCHEMA, TABLE_NAME, TC.CONSTRAINT_NAME AS ForeignKey, CONSTRAINT_TYPE, UNIQUE_CONSTRAINT_NAME AS ParentKey 
FROM
INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC, INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC 
WHERE 
TC.CONSTRAINT_NAME = RC.CONSTRAINT_NAME 
AND
TC.TABLE_NAME = 'EmployeePayHistory' 
AND
TC.CONSTRAINT_TYPE = 'FOREIGN KEY';
-- OR
SELECT CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE TABLE_NAME = 'EmployeePayHistory' AND CONSTRAINT_TYPE = 'FOREIGN KEY';

--  Find DB's in your SQL Instance
EXEC sp_databases;

-- Random Selects
SELECT * from Person.Person where FirstName ='Rob' OR FirstName = 'Roberto';

SELECT TOP(10) * FROM Sales.SalesOrderDetail;

SELECT COUNT(*) AS recordCnt FROM HumanResources.EmployeePayHistory;


